site_name: pytest helm charts
repo_name: "giantswarm/pytest-helm-charts"
site_url: https://github.com/giantswarm/pytest-helm-charts
theme:
  name: "readthedocs"

plugins:
  - search
  - mkapi

markdown_extensions:
  - admonition

nav:
  - Home:
      - Main: index.md
      - Fixtures: fixtures.md
  - API: $api/pytest_helm_charts.***
  - Examples:
      - Basic: "examples/basic.md"
      - Giant Swarm App Platform: "examples/giantswarm.md"
  - About:
      - "License": "license.md"
      - "Changelog": "CHANGELOG.md"
